-- Snowflake Setup Script for Olist Analytics dbt Project
-- Run in Snowsight as ACCOUNTADMIN

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS DBT_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS OLIST_ANALYTICS;
USE DATABASE OLIST_ANALYTICS;

CREATE SCHEMA IF NOT EXISTS RAW_OLIST;

CREATE ROLE IF NOT EXISTS DBT_ROLE;
GRANT USAGE ON WAREHOUSE DBT_WH TO ROLE DBT_ROLE;
GRANT ALL ON DATABASE OLIST_ANALYTICS TO ROLE DBT_ROLE;
GRANT ALL ON ALL SCHEMAS IN DATABASE OLIST_ANALYTICS TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE SCHEMAS IN DATABASE OLIST_ANALYTICS TO ROLE DBT_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA OLIST_ANALYTICS.RAW_OLIST TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA OLIST_ANALYTICS.RAW_OLIST TO ROLE DBT_ROLE;

-- Grant the role to your user (replace YOUR_USERNAME)
-- GRANT ROLE DBT_ROLE TO USER YOUR_USERNAME;